### ISSUE TITLE
Crash on sighting compass initialize

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1162]
Only one user reported this and they said it only happened once (the first time trying to use this feature in version 3.4.0). It wouldn't hurt to add a check for the lifecycle state before trying to start the camera.

Message: Trying to create LifecycleCamera with destroyed lifecycle.

java.lang.IllegalArgumentException: Trying to create LifecycleCamera with destroyed lifecycle.
at androidx.camera.lifecycle.b.a(:34)
at androidx.appcompat.widget.y0.b(:37)
at androidx.appcompat.widget.y0.run(:53)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by kylecorry31** [comment]
I believe this crash is fixed - I could not reproduce the issue though.
