### ISSUE TITLE
File too large to import (beacon GPX import)

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1170]
I received this report from one user. I don't know how large this file was - or even if it was a GPX file (it was > 200 MB), but I can update Andromeda to parse the file line by line instead of reading the whole file (similar to the Geospatial PDF parsing)

java.lang.OutOfMemoryError: Failed to allocate a 268501000 byte allocation with 25165824 free bytes and 85MB until OOM, target footprint 203838040, growth limit 268435456
at java.util.Arrays.copyOf(Arrays.java:3257)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
at java.lang.StringBuffer.append(StringBuffer.java:367)
at java.io.StringWriter.write(StringWriter.java:94)
at x4.e.z(:1)
at com.kylecorry.andromeda.files.ExternalFiles$read$2.q(Unknown Source:41)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.k(:3)
at jc.c0.run(Unknown Source:86)
at kotlinx.coroutines.scheduling.CoroutineScheduler.A(Unknown Source:0)
at kotlinx.coroutines.scheduling.CoroutineScheduler$a.run(:5)

**Comment by kylecorry31** [comment]
GPX parsing has been converted to treat the file as a stream instead of reading the text, which will at least save some memory as the file is parsed.

Other than that, if the file is huge, there is nothing that can be done since the waypoints need to be loaded into memory (other than alerting the user that the file is too big).
