### ISSUE TITLE
Crash while reducing map size

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1184]
This was reported by one user while reducing the size of a map (probably on import)

java.lang.NullPointerException: Options().run {
...ile(path, this)
} must not be null
at com.kylecorry.trail_sense.tools.maps.infrastructure.reduce.BaseMapReduce.com.kylecorry.andromeda.core.bitmap.BitmapUtils.decodeBitmapScaled(:9)
                                                                            reduce$suspendImpl
at com.kylecorry.trail_sense.tools.maps.ui.MapListFragment$mapFromUri$1$1.com.kylecorry.trail_sense.tools.maps.infrastructure.reduce.BaseMapReduce.reduce(:53)
                                                                          invokeSuspend
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(:3)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:86)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(:5)
                                                           runWorker
                                                           run

**Comment by kylecorry31** [comment]
I am unable to reproduce this issue. Based on the error message, it appears that the file path was null - analyzing the code, I can't find a code path that would lead to this, as any failure to save the map file results in either a short circuit (and toast), or an exception - both of which would happen before it reaches this line of code. 

I'll keep an eye out, but lowering this in priority since only a single user was affected.
