### ISSUE TITLE
Crash on resume (ScanQRFragment)

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1185]
This is normally a 1 time issue (I've had a handful of reports on different tools).

java.lang.RuntimeException: Unable to resume activity {com.kylecorry.trail_sense/com.kylecorry.trail_sense.MainActivity}: java.util.concurrent.CancellationException: Task was cancelled.
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4757)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4790)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.util.concurrent.CancellationException: Task was cancelled.
at androidx.concurrent.futures.AbstractResolvableFuture.e(:1)
at androidx.concurrent.futures.AbstractResolvableFuture.get(Unknown Source:21)
at androidx.concurrent.futures.CallbackToFutureAdapter$c.get(Unknown Source:2)
at z.d.get(Unknown Source:2)
at z.b.get(Unknown Source:25)
at b5.a.B(:6)
at g5.a.n(Unknown Source:19)
at com.kylecorry.trail_sense.shared.views.CameraView.b(:2)
at com.kylecorry.trail_sense.tools.qr.ui.ScanQRFragment.G0(:2)
at com.kylecorry.trail_sense.tools.qr.ui.ScanQRFragment.V(:5)
at androidx.fragment.app.d0.n(:4)
at androidx.fragment.app.d0.k(:2)
at androidx.fragment.app.FragmentManager.T(:1)
at androidx.fragment.app.FragmentManager.w(:3)
at androidx.fragment.app.d0.n(:7)
at androidx.fragment.app.d0.k(:2)
at androidx.fragment.app.FragmentManager.T(:1)
at androidx.fragment.app.FragmentManager.w(:3)
at androidx.fragment.app.p.onPostResume(:5)
at d.e.onPostResume(Unknown Source:0)
at android.app.Activity.performResume(Activity.java:8215)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4747)
... 13 more

**Comment by kylecorry31** [comment]
The fix for 3.5.1 did not resolve this - more research is needed on the cause

**Comment by kylecorry31** [comment]
A similar issue was fixed for the workmanager class by doing the following: https://android-review.googlesource.com/c/platform/frameworks/support/+/787406/2/work/workmanager/src/main/java/androidx/work/impl/WorkerWrapper.java

**Comment by kylecorry31** [comment]
I believe this is fixed now and is scheduled for the next release. I still can't reproduce the issue though, so I will keep this open to confirm no more error reports come in
