### ISSUE TITLE
Camera issue on version 3.9.0

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1272]
This was reported by a single user - it occurs every time they use the sighting compass. It previously worked on 3.8.0 for them, and clearing the cache or reinstalling does not help. Installed via F-Droid.

Message: dlopen failed: couldn't map "/mnt/asec/com.kylecorry.trail_sense-1/base.apk!/lib/arm64-v8a/[libimage_processing_util_jni.so](http://libimage_processing_util_jni.so/)" segment 2: Permission denied

java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/com.kylecorry.trail_sense-1/base.apk!/lib/arm64-v8a/[libimage_processing_util_jni.so](http://libimage_processing_util_jni.so/)" segment 2: Permission denied
at java.lang.Runtime.loadLibrary0([Runtime.java:1016](http://runtime.java:1016/))
at java.lang.System.loadLibrary([System.java:1657](http://system.java:1657/))
at [androidx.camera](http://androidx.camera/).core.ImageProcessingUtil.<clinit>(Unknown Source:2)
at [androidx.camera](http://androidx.camera/).core.ImageProcessingUtil.b(Unknown Source:0)
at [androidx.camera](http://androidx.camera/).core.i.c(Unknown Source:70)
at [androidx.camera](http://androidx.camera/).core.j.f(Unknown Source:60)
at [androidx.camera](http://androidx.camera/).core.i.a(Unknown Source:6)
at v.g0.a(:1)
at [v.b.run](http://v.b.run/)(:24)
at java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1162](http://threadpoolexecutor.java:1162/))
at java.util.concurrent.ThreadPoolExecutor$[Worker.run](http://worker.run/)([ThreadPoolExecutor.java:636](http://threadpoolexecutor.java:636/))
at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:764](http://thread.java:764/))

Another issue reported by a second user:
Message: Attempt to invoke interface method 'w.n androidx.camera.core.impl.CameraInternal.c()' on a null object reference

java.lang.NullPointerException: Attempt to invoke interface method 'w.n androidx.camera.core.impl.CameraInternal.c()' on a null object reference
at androidx.camera.core.UseCase.g(Unknown Source:0)
at androidx.camera.core.k.H(Unknown Source:65)
at p.r.run(:1)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by kylecorry31** [comment]
Best course of action will be to revert the version update of the camerax dependencies, it appears that isn't a stable build.

**Comment by kylecorry31** [comment]
I believe this is fixed now (since 3.8.0 worked fine with beta01/beta02 code)
