### ISSUE TITLE
Error on weather settings

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1323]
As reported by 2 users on the weather settings, I am unable to reproduce it.

Trail Sense: 4.2.0
Android SDK: 23
Device: samsung trltexx (SM-N910F)
Fragment: WeatherSettingsFragment
Diagnostics: BatteryUsageRestricted, CameraNoPermission

Trail Sense: 3.10.0
Android SDK: 23
Device: samsung kltexx (SM-G900F)
Fragment: WeatherSettingsFragment
Diagnostics: BatteryUsageRestricted, CameraNoPermission

Message: Binary XML file line #20: Binary XML file line #20: Error inflating class android.widget.TimePicker

android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class android.widget.TimePicker
at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
at android.app.TimePickerDialog.<init>(TimePickerDialog.java:147)
at android.app.TimePickerDialog.<init>(TimePickerDialog.java:107)
at com.kylecorry.trail_sense.settings.ui.d.e(SourceFile:8)
at androidx.preference.Preference.y(SourceFile:3)
at androidx.preference.Preference$a.onClick(SourceFile)
at android.view.View.performClick(View.java:5697)
at android.view.View$PerformClick.run(View.java:22526)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker
at android.view.LayoutInflater.createView(LayoutInflater.java:657)
at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:706)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:774)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
... 16 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at android.view.LayoutInflater.createView(LayoutInflater.java:631)
... 21 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.widget.TimePicker$TimePickerDelegate.onRtlPropertiesChanged(int)' on a null object reference
at android.widget.TimePicker.onRtlPropertiesChanged(TimePicker.java:248)
at android.view.View.resolvePadding(View.java:15608)
at android.view.ViewGroup.resolvePadding(ViewGroup.java:6875)
at android.view.View.initializeScrollbarsInternal(View.java:5341)
at android.view.View.<init>(View.java:4676)
at android.view.ViewGroup.<init>(ViewGroup.java:589)
at android.widget.FrameLayout.<init>(FrameLayout.java:97)
at android.widget.TimePicker.<init>(TimePicker.java:78)
at android.widget.TimePicker.<init>(TimePicker.java:74)
at android.widget.TimePicker.<init>(TimePicker.java:70)
... 23 more

**Comment by kylecorry31** [comment]
This may be a samsung specific issue?

**Comment by kylecorry31** [comment]
This has not been reported again in over a year - I'm not sure of the cause or what fixed it (unless it is very rare)
