### ISSUE TITLE
Error loading camerax library

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1449]
Trail Sense: 4.3.1
Android SDK: 26
Device: samsung
Fragment: NavigatorFragment
Diagnostics: BatteryUsageRestricted, GPSUnavailable

Message: dlopen failed: couldn't map "/mnt/asec/com.kylecorry.trail_sense-1/base.apk!/lib/armeabi-v7a/libimage_processing_util_jni.so" segment 2: Permission denied

java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/com.kylecorry.trail_sense-1/base.apk!/lib/armeabi-v7a/libimage_processing_util_jni.so" segment 2: Permission denied
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1657)
at androidx.camera.core.ImageProcessingUtil.<clinit>(Unknown Source:2)
at androidx.camera.core.ImageProcessingUtil.b(Unknown Source:0)
at androidx.camera.core.j.b(Unknown Source:70)
at androidx.camera.core.k.e(Unknown Source:60)
at androidx.camera.core.j.f(Unknown Source:6)
at v.h0.f(Unknown Source:7)
at v.b.run(SourceFile:26)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by kylecorry31** [comment]
https://stackoverflow.com/questions/42669800/permission-denied-for-so-files

**Comment by kylecorry31** [comment]
https://github.com/algolia/algoliasearch-client-android/issues/576#issuecomment-494148605

https://github.com/android/ndk/issues/979
