### ISSUE TITLE
Exception on maps view

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1627]
MapsFragment, 4.10.0, reported by 1 user

java.lang.NullPointerException
at com.kylecorry.trail_sense.tools.maps.ui.OfflineMapView.onDraw(SourceFile:146)
at android.view.View.draw(View.java:23898)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:30)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at androidx.fragment.app.FragmentContainerView.drawChild(Unknown Source:24)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(Unknown Source:35)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:30)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at androidx.fragment.app.FragmentContainerView.drawChild(Unknown Source:24)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(Unknown Source:35)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at androidx.fragment.app.FragmentContainerView.drawChild(Unknown Source:24)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(Unknown Source:35)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:30)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(Unknown Source:13)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22753)
at android.view.View.draw(View.java:23628)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.draw(View.java:23901)
at com.android.internal.policy.DecorView.draw(DecorView.java:1377)
at android.view.View.updateDisplayListIfDirty(View.java:22767)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:5414)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5122)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4186)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2893)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10445)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
at android.view.Choreographer.doCallbacks(Choreographer.java:866)
at android.view.Choreographer.doFrame(Choreographer.java:797)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by kylecorry31** [comment]
Reported by another user on 4.14.0:

java.lang.NullPointerException
at com.kylecorry.trail_sense.tools.maps.ui.PhotoMapView.onDraw(SourceFile:154)
at android.view.View.draw(View.java:22765)
at android.view.View.updateDisplayListIfDirty(View.java:21640)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:28)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at androidx.fragment.app.FragmentContainerView.drawChild(Unknown Source:32)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(Unknown Source:35)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:28)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at androidx.fragment.app.FragmentContainerView.drawChild(Unknown Source:32)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(Unknown Source:35)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at androidx.fragment.app.FragmentContainerView.drawChild(Unknown Source:32)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at androidx.fragment.app.FragmentContainerView.dispatchDraw(Unknown Source:35)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(Unknown Source:28)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(Unknown Source:13)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at android.view.View.updateDisplayListIfDirty(View.java:21631)
at android.view.View.draw(View.java:22496)
at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
at android.view.View.draw(View.java:22768)
at com.android.internal.policy.DecorView.draw(DecorView.java:852)
at android.view.View.updateDisplayListIfDirty(View.java:21640)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4557)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4285)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3434)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2234)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8884)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
at android.view.Choreographer.doCallbacks(Choreographer.java:845)
at android.view.Choreographer.doFrame(Choreographer.java:780)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:329)
at android.app.ActivityThread.main(ActivityThread.java:8063)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Comment by kylecorry31** [comment]
Closing, unable to reproduce and the PhotoMapView has been simplified so hopefully that resolves it
