### ISSUE TITLE
Concurrent modification exception

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1913]
Reported by 1 user - the location of this issue is odd, seems to be coming from the Android LocationManager itself. Maybe I can just synchronize the adding of that listener.

java.util.ConcurrentModificationException
at android.util.ArrayMap.put(ArrayMap.java:561)
at android.location.LocationManager.addNmeaListener(LocationManager.java:2081)
at g1.d.r(Unknown Source:0)
at com.kylecorry.andromeda.location.a.A(SourceFile:98)
at com.kylecorry.andromeda.core.sensors.AbstractSensor$topic$1.a(SourceFile:5)
at com.kylecorry.andromeda.core.topics.Topic$Companion$lazy$1.h(SourceFile:19)
at com.kylecorry.andromeda.core.topics.c.q(Unknown Source:28)
at com.kylecorry.andromeda.core.topics.a.q(Unknown Source:10)
at com.kylecorry.trail_sense.shared.sensors.b.A(SourceFile:24)
at com.kylecorry.andromeda.core.sensors.AbstractSensor$topic$1.a(SourceFile:5)
at com.kylecorry.andromeda.core.topics.Topic$Companion$lazy$1.h(SourceFile:19)
at com.kylecorry.andromeda.core.topics.c.q(Unknown Source:28)
at com.kylecorry.andromeda.core.topics.a.q(Unknown Source:10)
at com.kylecorry.trail_sense.shared.sensors.altimeter.c.A(SourceFile:22)
at com.kylecorry.andromeda.core.sensors.AbstractSensor$topic$1.a(SourceFile:5)
at com.kylecorry.andromeda.core.topics.Topic$Companion$lazy$1.h(SourceFile:19)
at com.kylecorry.andromeda.core.topics.c.q(Unknown Source:28)
at com.kylecorry.andromeda.core.topics.a.q(Unknown Source:10)
at com.kylecorry.trail_sense.shared.sensors.altimeter.b.A(SourceFile:13)
at com.kylecorry.andromeda.core.sensors.AbstractSensor$topic$1.a(SourceFile:5)
at com.kylecorry.andromeda.core.topics.Topic$Companion$lazy$1.h(SourceFile:19)
at com.kylecorry.andromeda.core.topics.c.q(Unknown Source:28)
at com.kylecorry.andromeda.core.topics.a.y(SourceFile:35)
at com.kylecorry.trail_sense.shared.sensors.SensorExtensionsKt$readAll$2$1$1.q(Unknown Source:30)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.f(Unknown Source:8)
at qe.z.run(Unknown Source:109)
at we.a.run(SourceFile:97)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [g1{Cancelling}@8f1a9f5, Dispatchers.Default]

**Comment by kylecorry31** [comment]
Upon further analysis, it appears that this is already in a synchronized block. More research is needed to see if this was an internal error or not. In the meantime, I can wrap it with a try/catch

**Comment by kylecorry31** [comment]
Added a try/catch in the latest version of Andromeda
