### ISSUE TITLE
Out of memory error on warp map fragment

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2020]
Reported by one user on 5.4.0

java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1130)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1088)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1038)
at android.graphics.Bitmap.createBitmap(Bitmap.java:999)
at p3.f.t(SourceFile:141)
at com.kylecorry.trail_sense.tools.maps.ui.WarpMapFragment$next$2.q(SourceFile:126)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.j(SourceFile:1)
at ve.y.run(SourceFile:1)
at androidx.appcompat.widget.j.run(SourceFile:821)
at bf.i.run(SourceFile:1)
at bf.a.run(SourceFile:97)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [f1{Cancelling}@796db0f, Dispatchers.Main.immediate]

**Comment by kylecorry31** [comment]
#1033 will use a different architecture and fix this
