### ISSUE TITLE
Crash when reopening while guide bottom sheet is open

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2423]
Not able to reproduce, but will try more things. Reported by 1 user.

ComponentInfo{com.kylecorry.trail_sense/com.kylecorry.trail_sense.main.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.kylecorry.trail_sense.tools.guide.ui.GuideBottomSheetFragment: could not find Fragment constructor

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kylecorry.trail_sense/com.kylecorry.trail_sense.main.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.kylecorry.trail_sense.tools.guide.ui.GuideBottomSheetFragment: could not find Fragment constructor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.kylecorry.trail_sense.tools.guide.ui.GuideBottomSheetFragment: could not find Fragment constructor
at M0.E.a(SourceFile:59)
at androidx.fragment.app.FragmentState.r(SourceFile:3)
at androidx.fragment.app.e.<init>(SourceFile:3)
at androidx.fragment.app.d.W(SourceFile:253)
at androidx.fragment.app.d.b(SourceFile:174)
at M0.v.a(SourceFile:139)
at c.j.onCreate(SourceFile:31)
at i.i.onCreate(SourceFile:1)
at com.kylecorry.trail_sense.main.MainActivity.onCreate(SourceFile:471)
at android.app.Activity.performCreate(Activity.java:8207)
at android.app.Activity.performCreate(Activity.java:8191)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
... 11 more
Caused by: java.lang.NoSuchMethodException: com.kylecorry.trail_sense.tools.guide.ui.GuideBottomSheetFragment.<init> []
at java.lang.Class.getConstructor0(Class.java:2332)
at java.lang.Class.getConstructor(Class.java:1728)
at M0.E.a(SourceFile:20)
... 23 more

**Comment by kylecorry31** [comment]
Not seen in over a year
