### ISSUE TITLE
Crash from cell signal sensor

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2616]
Reported by 1 user on the diagnostics tool (may have come from backtrack though).

TS 6.4.0

Android SDK 29

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Throwable android.os.ParcelableException.getCause()' on a null object reference
	at android.telephony.TelephonyManager$1.lambda$onError$2(TelephonyManager.java:5319)
	at android.telephony.-$$Lambda$TelephonyManager$1$DUDjwoHWG36BPTvbfvZqnIO3Y88.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by kylecorry31** [comment]
Looks like this is a known issue on Android 10 that was later fixed, but not all devices got the update: https://issuetracker.google.com/issues/141438333

**Comment by kylecorry31** [comment]
SDK 29: [Workaround ](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r29:frameworks/base/telephony/java/android/telephony/TelephonyManager.java;l=5352)

SDK 30: https://cs.android.com/android/platform/superproject/+/android-10.0.0_r30:frameworks/base/telephony/java/android/telephony/TelephonyManager.java;l=5358

Solution should be to create a wrapper around the executor that handles exceptions.
